services:
  bot:
    build: .
    container_name: coffee-bot
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      API_ENABLED: "true"
      DATABASE_URL: postgresql://coffee_bot:coffee_bot@db:5432/coffee_bot
      HTTP_HOST: 0.0.0.0
      HTTP_PORT: 3000
      LOG_FILE_PATH: /app/logs/app.log
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - /var/log/coffee-bot:/app/logs
    networks:
      - default
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.coffee-bot.rule=Host(`miniapp.dragonzzz.ru`)
      - traefik.http.routers.coffee-bot.entrypoints=web,websecure
      - traefik.http.routers.coffee-bot.tls=true
      - traefik.http.routers.coffee-bot.tls.certresolver=mytlschallenge
      - traefik.http.services.coffee-bot.loadbalancer.server.port=3000
  db:
    image: postgres:16-alpine
    container_name: coffee-bot-db
    environment:
      POSTGRES_DB: coffee_bot
      POSTGRES_USER: coffee_bot
      POSTGRES_PASSWORD: coffee_bot
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coffee_bot -d coffee_bot"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - coffee-bot-db:/var/lib/postgresql/data

volumes:
  coffee-bot-db:
networks:
  traefik-public:
    external: true
